kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: quotes
spec:
  host: quotes-254500-magr.apps.exoscale-ch-gva-2-0.appuio.cloud
  to:
    kind: Service
    name: quotes
    weight: 100
  port:
    targetPort: 10000-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
